//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogixGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogixGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:I.Ch{2}Data.
        /// </summary>
        internal static string addressAI {
            get {
                return ResourceManager.GetString("addressAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:O.Ch{2}Data.
        /// </summary>
        internal static string addressAO {
            get {
                return ResourceManager.GetString("addressAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:I.Data.{2}.
        /// </summary>
        internal static string addressDI {
            get {
                return ResourceManager.GetString("addressDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}:O.Data.{2}.
        /// </summary>
        internal static string addressDO {
            get {
                return ResourceManager.GetString("addressDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1},{2}].
        /// </summary>
        internal static string alarmData {
            get {
                return ResourceManager.GetString("alarmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION DUCO_AI_AOI (Description := &quot;Analog Input Data Processing&quot;,
        ///	                                           Revision := &quot;1.0&quot;,
        ///	                                           ExecutePrescan := No,
        ///	                                           ExecutePostscan := No,
        ///	                                           ExecuteEnableInFalse := No,
        ///	                                           CreatedDate := &quot;2016-03-30T20:32:15.687Z&quot;,
        ///	                                           CreatedBy := &quot;Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_AI {
            get {
                return ResourceManager.GetString("aoi_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION
        ///	
        ///	DUCO_Alarm_AOI (Revision := &quot;1.0&quot;,
        ///	                                              ExecutePrescan := No,
        ///	                                              ExecutePostscan := No,
        ///	                                              ExecuteEnableInFalse := No,
        ///	                                              CreatedDate := &quot;2016-03-31T17:03:22.203Z&quot;,
        ///	                                              CreatedBy := &quot;Mark Dodd&quot;,
        ///	                                              EditedDate  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_Alarm {
            get {
                return ResourceManager.GetString("aoi_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION DUCO_ALARM_CTL_AOI (Revision := &quot;1.0&quot;,
        ///	                                                  ExecutePrescan := No,
        ///	                                                  ExecutePostscan := No,
        ///	                                                  ExecuteEnableInFalse := No,
        ///	                                                  CreatedDate := &quot;2016-04-04T21:48:00.640Z&quot;,
        ///	                                                  CreatedBy := &quot;WATSONPLC\Maintenance&quot;,
        ///	                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_Alarm_CTL {
            get {
                return ResourceManager.GetString("aoi_Alarm_CTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION DUCO_DI_AOI (Description := &quot;Duco Design$NDiscrete Input Instruction&quot;,
        ///	                                           Revision := &quot;1.0&quot;,
        ///	                                           ExecutePrescan := No,
        ///	                                           ExecutePostscan := No,
        ///	                                           ExecuteEnableInFalse := No,
        ///	                                           CreatedDate := &quot;2016-04-01T15:43:12.375Z&quot;,
        ///	                                           Creat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_DI {
            get {
                return ResourceManager.GetString("aoi_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION Duco_SP_RAMP (Revision := &quot;1.0&quot;,
        ///	                                          Vendor := &quot;Kilowatts Deisgn Company Ltd.&quot;,
        ///	                                          ExecutePrescan := No,
        ///	                                          ExecutePostscan := No,
        ///	                                          ExecuteEnableInFalse := No,
        ///	                                          CreatedDate := &quot;2012-03-18T10:22:44.613Z&quot;,
        ///	                                          CreatedBy := &quot;Mark Dodd&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_Duco_SP_Ramp {
            get {
                return ResourceManager.GetString("aoi_Duco_SP_Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION Duco_High_Low_Select (Revision := &quot;1.0&quot;,
        ///	                                                  ExecutePrescan := No,
        ///	                                                  ExecutePostscan := No,
        ///	                                                  ExecuteEnableInFalse := No,
        ///	                                                  CreatedDate := &quot;2012-10-01T22:54:42.578Z&quot;,
        ///	                                                  CreatedBy := &quot;Mark Dodd&quot;,
        ///	                                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_High_Low_Select {
            get {
                return ResourceManager.GetString("aoi_High_Low_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION RUN_HOURS (Revision := &quot;1.0&quot;,
        ///	                                         ExecutePrescan := No,
        ///	                                         ExecutePostscan := No,
        ///	                                         ExecuteEnableInFalse := No,
        ///	                                         CreatedDate := &quot;2012-03-09T10:12:44.142Z&quot;,
        ///	                                         CreatedBy := &quot;Mark Dodd&quot;,
        ///	                                         EditedDate := &quot;2013-03-19T20:02:06.221Z&quot;,
        ///	        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_Run_Hours {
            get {
                return ResourceManager.GetString("aoi_Run_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	ADD_ON_INSTRUCTION_DEFINITION
        ///
        ///	DUCO_SCP_AOI (Revision := &quot;1.0&quot;,
        ///	                                            ExecutePrescan := No,
        ///	                                            ExecutePostscan := No,
        ///	                                            ExecuteEnableInFalse := No,
        ///	                                            CreatedDate := &quot;2013-01-04T18:13:36.446Z&quot;,
        ///	                                            CreatedBy := &quot;Mark Dodd&quot;,
        ///	                                            EditedDate := &quot;2016-04-01T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoi_SCP {
            get {
                return ResourceManager.GetString("aoi_SCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END_CONTROLLER.
        /// </summary>
        internal static string controllerFooter {
            get {
                return ResourceManager.GetString("controllerFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER {0} (ProcessorType := &quot;{1}&quot;,
        ///                             Major := 20,
        ///                             TimeSlice := 20,
        ///                             ShareUnusedTimeSlice := 1,
        ///                             RedundancyEnabled := 0,
        ///                             KeepTestEditsOnSwitchOver := 0,
        ///                             DataTablePadPercentage := 50,
        ///                             SecurityCode := 0,
        ///                             ChangesToDetect := 16#ffff_ffff_ffff_ffff,
        ///                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ctl_Controller_Definition {
            get {
                return ResourceManager.GetString("ctl_Controller_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*********************************************
        ///
        ///  Import-Export
        ///  Version   := RSLogix 5000 v20.01
        ///  Owner     := operator, 
        ///  Exported  := Thu Apr 07 09:08:29 2016
        ///
        ///  Note:  File encoded in UTF-8.  Only edit file in a program 
        ///         which supports UTF-8 (like Notepad, not Wordpad).
        ///
        ///**********************************************)
        ///IE_VER := 2.11;
        ///.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/alarm&gt;.
        /// </summary>
        internal static string hmiAlarmFooter {
            get {
                return ResourceManager.GetString("hmiAlarmFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;alarm history-size=&quot;128&quot; display-name=&quot;[ALARM]&quot; hold-time=&quot;250&quot; max-update-rate=&quot;1.00&quot; embedded-server-update-rate=&quot;1.00&quot; silence-tag=&quot;&quot; remote-silence-exp=&quot;&quot; remote-ack-all-exp=&quot;&quot; status-reset-tag=&quot;&quot; remote-status-reset-exp=&quot;&quot; close-display-tag=&quot;&quot; remote-close-display-exp=&quot;&quot;&gt;.
        /// </summary>
        internal static string hmiAlarmHeader {
            get {
                return ResourceManager.GetString("hmiAlarmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/alarms&gt;.
        /// </summary>
        internal static string hmiAlarmsFooter {
            get {
                return ResourceManager.GetString("hmiAlarmsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;alarms version=&quot;1.0&quot; product=&quot;{E44CB020-C21D-11D3-8A3F-0010A4EF3494}&quot; id=&quot;Alarms&quot;&gt;.
        /// </summary>
        internal static string hmiAlarmsHeader {
            get {
                return ResourceManager.GetString("hmiAlarmsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;.
        /// </summary>
        internal static string hmiFileHeader {
            get {
                return ResourceManager.GetString("hmiFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;message id=&quot;{0}&quot; trigger-value=&quot;1&quot; trigger=&quot;#{1}&quot; backcolor=&quot;{3}&quot; forecolor=&quot;{4}&quot; audio=&quot;false&quot; display=&quot;true&quot; print=&quot;false&quot; message-to-tag=&quot;false&quot; text=&quot;{2}&quot;/&gt;.
        /// </summary>
        internal static string hmiMessages {
            get {
                return ResourceManager.GetString("hmiMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/messages&gt;.
        /// </summary>
        internal static string hmiMessagesFooter {
            get {
                return ResourceManager.GetString("hmiMessagesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;messages&gt;.
        /// </summary>
        internal static string hmiMessagesHeader {
            get {
                return ResourceManager.GetString("hmiMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;trigger id=&quot;{0}&quot; type=&quot;value&quot; ack-all-value=&quot;0&quot; use-ack-all=&quot;false&quot; ack-tag=&quot;&quot; exp=&quot;{{[PLC]{1}}}&quot; message-tag=&quot;&quot; message-handshake-exp=&quot;&quot; message-notification-tag=&quot;&quot; remote-ack-exp=&quot;&quot; remote-ack-handshake-tag=&quot;&quot; label=&quot;{2}&quot; handshake-tag=&quot;&quot;/&gt;.
        /// </summary>
        internal static string hmiTriggers {
            get {
                return ResourceManager.GetString("hmiTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/triggers&gt;.
        /// </summary>
        internal static string hmiTriggersFooter {
            get {
                return ResourceManager.GetString("hmiTriggersFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;triggers&gt;.
        /// </summary>
        internal static string hmiTriggersHeader {
            get {
                return ResourceManager.GetString("hmiTriggersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					N: MOV({0},{1}.Raw)DUCO_AI_AOI({1}_AOI,{1},ALARMS);.
        /// </summary>
        internal static string logic_AI {
            get {
                return ResourceManager.GetString("logic_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					N: MOV({0},{1});.
        /// </summary>
        internal static string logic_AO {
            get {
                return ResourceManager.GetString("logic_AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					N: DUCO_SCP_AOI({0}_SCP,{0},0.0,100.0,4000,20000,{1});.
        /// </summary>
        internal static string logic_AO1769 {
            get {
                return ResourceManager.GetString("logic_AO1769", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					N: XIC({0})OTE({1}.Raw);
        ///					N: DUCO_DI_AOI({1}_AOI,{1},ALARMS);.
        /// </summary>
        internal static string logic_DI {
            get {
                return ResourceManager.GetString("logic_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					N: XIC({0})OTE({1});.
        /// </summary>
        internal static string logic_DO {
            get {
                return ResourceManager.GetString("logic_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			ROUTINE a_Main 
        ///					N: NOP();
        ///					N: DUCO_ALARM_CTL_AOI(MASTER_ALARMS,ALARMS);
        ///					N: JSR(b_Program_Cfg,0);
        ///					N: JSR({0},0)JSR({1},0);
        ///			END_ROUTINE
        ///.
        /// </summary>
        internal static string logic_Main {
            get {
                return ResourceManager.GetString("logic_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			ROUTINE a_Main 
        ///					N: NOP();
        ///					N: JSR({0},0);
        ///					N: JSR({1},0);
        ///			END_ROUTINE
        ///.
        /// </summary>
        internal static string logic_Main_Outputs {
            get {
                return ResourceManager.GetString("logic_Main_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM OutputConditioning (MAIN := &quot;a_Main&quot;,
        ///	                          MODE := 0,
        ///	                          DisableFlag := 0)
        ///			TAG
        ///			END_TAG.
        /// </summary>
        internal static string logic_OutputConditioningHeader {
            get {
                return ResourceManager.GetString("logic_OutputConditioningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			ROUTINE b_Program_Cfg 
        ///					N: GSV(WallClockTime,,LocalDateTime,udt_Clock.Year);
        ///			END_ROUTINE.
        /// </summary>
        internal static string logic_ProgramCfg {
            get {
                return ResourceManager.GetString("logic_ProgramCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM InputConditoning (MAIN := &quot;a_Main&quot;,
        ///	                          MODE := 0,
        ///	                          DisableFlag := 0)
        ///			TAG
        ///			END_TAG.
        /// </summary>
        internal static string logic_ProgramHeader {
            get {
                return ResourceManager.GetString("logic_ProgramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d_AnalogInputs.
        /// </summary>
        internal static string logicAIName {
            get {
                return ResourceManager.GetString("logicAIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d_AnalogOutputs.
        /// </summary>
        internal static string logicAOName {
            get {
                return ResourceManager.GetString("logicAOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c_DiscreteInputs.
        /// </summary>
        internal static string logicDIName {
            get {
                return ResourceManager.GetString("logicDIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c_DiscreteOutputs.
        /// </summary>
        internal static string logicDOName {
            get {
                return ResourceManager.GetString("logicDOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END_ROUTINE.
        /// </summary>
        internal static string logicFooter {
            get {
                return ResourceManager.GetString("logicFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROUTINE .
        /// </summary>
        internal static string logicLadderHeader {
            get {
                return ResourceManager.GetString("logicLadderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1756-L72
        ///1756-L73
        ///1756-L74
        ///1769-L30ER.
        /// </summary>
        internal static string ProcessorList {
            get {
                return ResourceManager.GetString("ProcessorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : DUCO_AI_DATA (Description:= {10}) := [0.0e+0,0.0e+0,0.0e+0,0,[{1},{2},{3},{4}],{5},{6},{7},{8},{9}];.
        /// </summary>
        internal static string tagAI {
            get {
                return ResourceManager.GetString("tagAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_AOI : DUCO_AI_AOI (Description:= Add on instruction for {1});.
        /// </summary>
        internal static string tagAIAOI {
            get {
                return ResourceManager.GetString("tagAIAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : REAL (Description := {1}) := 0;.
        /// </summary>
        internal static string tagAO {
            get {
                return ResourceManager.GetString("tagAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_SCP : DUCO_SCP_AOI;.
        /// </summary>
        internal static string tagAOSCP {
            get {
                return ResourceManager.GetString("tagAOSCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : DUCO_DI_DATA (Description:= {2})  := [0,{1}];.
        /// </summary>
        internal static string tagDI {
            get {
                return ResourceManager.GetString("tagDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_AOI : DUCO_DI_AOI (Description:= Add on instruction for {1});.
        /// </summary>
        internal static string tagDIAOI {
            get {
                return ResourceManager.GetString("tagDIAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : BOOL(Description := {1}) := 0;.
        /// </summary>
        internal static string tagDO {
            get {
                return ResourceManager.GetString("tagDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	TASK FastTask (Type := PERIODIC,
        ///	               Rate := 100,
        ///	               Priority := 1,
        ///	               Watchdog := 500,
        ///	               DisableUpdateOutputs := No,
        ///	               InhibitTask := No)
        ///			InputConditoning;
        ///			OutputConditioning;
        ///	END_TASK.
        /// </summary>
        internal static string task_FastTask {
            get {
                return ResourceManager.GetString("task_FastTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_AI_CFG (Description := &quot;Duco Design$NAnalog Input Configuration$NUser Define Data Type&quot;,
        ///	                      FamilyType := NoFamily)
        ///		DUCO_Limits PV (Description := &quot;PV Engineering Units$N Min / Max&quot;);
        ///		DUCO_Limits Raw (Description := &quot;Raw Input Min / Max&quot;);
        ///		DUCO_Limits Fail (Description := &quot;Failure Setpoint Min/Max (mA)&quot;);
        ///		REAL Hysterisis (Description := &quot;Alarm Hysterisis&quot;);
        ///	END_DATATYPE.
        /// </summary>
        internal static string udt_Duco_AI_CFG {
            get {
                return ResourceManager.GetString("udt_Duco_AI_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_AI_DATA (Description := &quot;Duco Design$NAnalog Input$NUser Define Data Type&quot;,
        ///	                       FamilyType := NoFamily)
        ///		REAL Raw (Description := &quot;Raw Input Value from Analog Input Module&quot;);
        ///		REAL PV (Description := &quot;Scaled Process Variable&quot;);
        ///		REAL mA (Description := &quot;Raw Input Converted to mili-amp&quot;);
        ///		SINT ZZZZZZZZZZDUCO_AI3 (Hidden := 1);
        ///		BIT Fault ZZZZZZZZZZDUCO_AI3 : 0 (Description := &quot;Analog Fault Bit (1 = OK)&quot;);
        ///		DUCO_AI_CFG CFG (Description := &quot;Analog Input Configur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_AI_Data {
            get {
                return ResourceManager.GetString("udt_Duco_AI_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_Alarm_Bits (Description := &quot;Duco Program Alarm Bit Management&quot;,
        ///	                          FamilyType := NoFamily)
        ///		SINT ZZZZZZZZZZDUCO_Alarm0 (Hidden := 1);
        ///		BIT HMI_ESD ZZZZZZZZZZDUCO_Alarm0 : 0 (Description := &quot;HMI ESD Bit&quot;);
        ///		BIT HMI_ACK ZZZZZZZZZZDUCO_Alarm0 : 1 (Description := &quot;HMI Acknowledge Bit&quot;);
        ///		BIT HMI_Reset ZZZZZZZZZZDUCO_Alarm0 : 2 (Description := &quot;HMI Reset Bit&quot;);
        ///		BIT HMI_Global_Reset ZZZZZZZZZZDUCO_Alarm0 : 3 (Description := &quot;HMI Global Reset Bit&quot;);
        ///		BIT Physica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_Alarm_Bits {
            get {
                return ResourceManager.GetString("udt_Duco_Alarm_Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_ALM (FamilyType := NoFamily)
        ///		SINT ZZZZZZZZZZDUCO_ALM0 (Hidden := 1);
        ///		BIT Enable ZZZZZZZZZZDUCO_ALM0 : 0 (Description := &quot;1 = Enable&quot;);
        ///		BIT FO_Enable ZZZZZZZZZZDUCO_ALM0 : 1 (Description := &quot;1 = Enable&quot;);
        ///		BIT Bypass ZZZZZZZZZZDUCO_ALM0 : 2 (Description := &quot;1 = Bypass&quot;);
        ///		BIT Condition ZZZZZZZZZZDUCO_ALM0 : 3 (Description := &quot;Alarm Conditioning (ie. Pump Run Status for a Low Pressure)&quot;);
        ///		BIT Latched ZZZZZZZZZZDUCO_ALM0 : 4 (Description := &quot;Latched Alarm (1 = OK, 0 = Alarm)&quot;);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_Alm {
            get {
                return ResourceManager.GetString("udt_Duco_Alm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE Duco_Clock (Description := &quot;Duco$NClock Data Type&quot;,
        ///	                     FamilyType := NoFamily)
        ///		DINT Year;
        ///		DINT Month;
        ///		DINT Day;
        ///		DINT Hour;
        ///		DINT Minute;
        ///		DINT Second;
        ///		DINT Microsecond;
        ///		DINT Day_of_Week;
        ///	END_DATATYPE
        ///.
        /// </summary>
        internal static string udt_Duco_Clock {
            get {
                return ResourceManager.GetString("udt_Duco_Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_DI_DATA (FamilyType := NoFamily)
        ///		SINT ZZZZZZZZZZDUCO_DI_DA0 (Hidden := 1);
        ///		BIT Input ZZZZZZZZZZDUCO_DI_DA0 : 0 (Description := &quot;Discrete Input Mapped from Channel&quot;);
        ///		BIT Raw ZZZZZZZZZZDUCO_DI_DA0 : 1 (Description := &quot;Raw Conditioned Input&quot;);
        ///		DUCO_ALM Alarm (Description := &quot;Duco Alarm Data Type&quot;);
        ///	END_DATATYPE
        ///.
        /// </summary>
        internal static string udt_Duco_DI_Data {
            get {
                return ResourceManager.GetString("udt_Duco_DI_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_LEADLAG_Interface (FamilyType := NoFamily)
        ///		SINT ZZZZZZZZZZKW_LEADLAG0 (Hidden := 1);
        ///		BIT A_Lead_CMD ZZZZZZZZZZKW_LEADLAG0 : 0 (Description := &quot;Pump A HMI Lead Command&quot;);
        ///		BIT A_Lag_CMD ZZZZZZZZZZKW_LEADLAG0 : 1 (Description := &quot;Pump A HMI Lag Command&quot;);
        ///		BIT B_Lead_CMD ZZZZZZZZZZKW_LEADLAG0 : 2 (Description := &quot;Pump B HMI Lead Command&quot;);
        ///		BIT B_Lag_CMD ZZZZZZZZZZKW_LEADLAG0 : 3 (Description := &quot;Pump B HMI Lag Command&quot;);
        ///		BIT A_LL_Stat ZZZZZZZZZZKW_LEADLAG0 : 4 (Description := &quot;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_LeadLag_Interface {
            get {
                return ResourceManager.GetString("udt_Duco_LeadLag_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_LeadLag_SP (Description := &quot;Lead Lag Setpoints&quot;,
        ///	                        FamilyType := NoFamily)
        ///		REAL LeadStart (Description := &quot;Lead Start Setpoint&quot;);
        ///		REAL LeadStop (Description := &quot;Lead Stop Setpoint&quot;);
        ///		REAL LagStart (Description := &quot;Lag Start Setpoint&quot;);
        ///		REAL LagStop (Description := &quot;Lag Stop Setpoint&quot;);
        ///	END_DATATYPE.
        /// </summary>
        internal static string udt_DUCO_LeadLag_SP {
            get {
                return ResourceManager.GetString("udt_DUCO_LeadLag_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_Limits (Description := &quot;Duco Analog Floating Point Limits Data Structure&quot;,
        ///	                      FamilyType := NoFamily)
        ///		REAL Min (Description := &quot;Minimum Value&quot;);
        ///		REAL Max (Description := &quot;Maximum Value&quot;);
        ///	END_DATATYPE.
        /// </summary>
        internal static string udt_Duco_Limits {
            get {
                return ResourceManager.GetString("udt_Duco_Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_Motor_Interface (FamilyType := NoFamily)
        ///		SINT ZZZZZZZZZZKW_Motor_I0 (Hidden := 1);
        ///		BIT HMI_Enable ZZZZZZZZZZKW_Motor_I0 : 0 (Description := &quot;HMI Enable Command&quot;);
        ///		BIT HMI_Disable ZZZZZZZZZZKW_Motor_I0 : 1 (Description := &quot;HMI Disable Command&quot;);
        ///		BIT Enable ZZZZZZZZZZKW_Motor_I0 : 2 (Description := &quot;Enable / Disable (1 = Enable)&quot;);
        ///		BIT Run_Status ZZZZZZZZZZKW_Motor_I0 : 3 (Description := &quot;Map the Run Status for the Motor Into this Point&quot;);
        ///		BIT HMI_Start ZZZZZZZZZZKW_Motor_I0 : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_Motor {
            get {
                return ResourceManager.GetString("udt_Duco_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DATATYPE DUCO_PIDE_Interface (FamilyType := NoFamily)
        ///		REAL PV (Description := &quot;Process Variable (Engineering Units)&quot;);
        ///		REAL PVMin (Description := &quot;Process Variable Minimum (Engineering Units)&quot;);
        ///		REAL PVMax (Description := &quot;Process Variable Maximum $N(Engineering Units)&quot;);
        ///		REAL PV_NormalL (Description := &quot;Process Variable Minimum Normal Operation Point (Engineering Units)&quot;);
        ///		REAL PV_NormalH (Description := &quot;Process Variable Maximum Normal Operation Point (Engineering Units)&quot;);
        ///		REAL SP (Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udt_Duco_PIDE_Interface {
            get {
                return ResourceManager.GetString("udt_Duco_PIDE_Interface", resourceCulture);
            }
        }
    }
}
